# Generated by Django 4.2.23 on 2025-10-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ماده اولیه')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='مقدار')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('threshold', models.FloatField(default=0, help_text='در صورت کمتر شدن مقدار از این حد، وضعیت هشدار می\u200cشود.', verbose_name='حد آستانه موجودی')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='تأمین\u200cکننده')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قطعه')),
                ('stock_cut', models.PositiveIntegerField(default=0, verbose_name='موجودی برش')),
                ('stock_cnc_tools', models.PositiveIntegerField(default=0, verbose_name='موجودی سی\u200cان\u200cسی و ابزار')),
                ('threshold', models.PositiveIntegerField(default=0, verbose_name='آستانه هشدار')),
                ('description', models.TextField(blank=True, help_text='توضیحات دلخواه برای قطعه (اختیاری)', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام مدل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مدل',
                'verbose_name_plural': 'مدل\u200cهای محصول',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_3a9fcc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=1, help_text='مقدار بر اساس واحد تعریف\u200cشده در ماده اولیه است.', max_digits=12, verbose_name='مقدار موردنیاز')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom', to='inventory.material', verbose_name='ماده اولیه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bom_items', to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزء (ماده اولیه) تشکیل\u200cدهنده',
                'verbose_name_plural': 'اجزاء (ماده اولیه) تشکیل\u200cدهندهٔ محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='تعداد موردنیاز')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bom', to='inventory.part', verbose_name='قطعه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزء (قطعه) تشکیل\u200cدهنده',
                'verbose_name_plural': 'اجزاء (قطعه) تشکیل\u200cدهندهٔ محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productmodel', verbose_name='مدل'),
        ),
        migrations.AddField(
            model_name='part',
            name='product_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='inventory.productmodel', verbose_name='مدل'),
        ),
    ]
