# Generated by Django 4.2.23 on 2025-10-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production_line', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='production_line.productionline', verbose_name='ایستگاه'),
        ),
        migrations.AddField(
            model_name='material',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='production_line.productionline', verbose_name='ایستگاه'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['product'], name='inventory_p_product_49c676_idx'),
        ),
        migrations.AddIndex(
            model_name='productmaterial',
            index=models.Index(fields=['material'], name='inventory_p_materia_7ea4b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.CheckConstraint(check=models.Q(('qty__gt', 0)), name='product_material_qty_gt_0'),
        ),
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product', 'material')},
        ),
        migrations.AddIndex(
            model_name='productcomponent',
            index=models.Index(fields=['product'], name='inventory_p_product_2edb44_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomponent',
            index=models.Index(fields=['part'], name='inventory_p_part_id_24182c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(check=models.Q(('qty__gte', 1)), name='product_component_qty_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='productcomponent',
            unique_together={('product', 'part')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_model'], name='inventory_p_product_129b66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'product_model')},
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['name'], name='inventory_p_name_c0a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['stage'], name='inventory_p_stage_i_7eaaec_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['product_model'], name='inventory_p_product_5ffbda_idx'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(('stock_cut__gte', 0)), name='part_stock_cut_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(('stock_cnc_tools__gte', 0)), name='part_stock_cnc_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(check=models.Q(('threshold__gte', 0)), name='part_threshold_gte_0'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('name', 'product_model')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='inventory_m_name_1014de_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['stage'], name='inventory_m_stage_i_168cf1_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('threshold__gte', 0)), name='material_threshold_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='material_price_gte_0_or_null'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='material_quantity_gte_0_or_null'),
        ),
    ]
