# Generated by Django 4.2.23 on 2025-10-22 11:48

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import production_line.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_workpage', models.IntegerField(default=0, verbose_name='موجودی صفحه\u200cکاری')),
                ('stock_undercoating', models.IntegerField(default=0, verbose_name='موجودی رنگ زیرکار')),
                ('stock_painting', models.IntegerField(default=0, verbose_name='موجودی رنگ')),
                ('stock_sewing', models.IntegerField(default=0, verbose_name='موجودی خیاطی')),
                ('stock_upholstery', models.IntegerField(default=0, verbose_name='موجودی رویه\u200cکوبی')),
                ('stock_assembly', models.IntegerField(default=0, verbose_name='موجودی مونتاژ')),
                ('stock_packaging', models.IntegerField(default=0, verbose_name='موجودی بسته\u200cبندی')),
                ('threshold', models.IntegerField(blank=True, default=0, null=True, verbose_name='حد آستانه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('produced_qty', models.PositiveIntegerField(default=0)),
                ('scrap_qty', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(choices=[('cutting', 'برش'), ('cnc_tools', 'سی\u200cان\u200cسی و ابزار'), ('undercoating', 'رنگ زیرکار'), ('painting', 'رنگ'), ('workpage', 'صفحه\u200cکاری'), ('sewing', 'خیاطی'), ('upholstery', 'رویه\u200cکوبی'), ('assembly', 'مونتاژ'), ('packaging', 'بسته\u200cبندی')], max_length=20)),
                ('is_scrap', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('jdate', django_jalali.db.models.jDateField(default=production_line.models.today_jdate)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.productionjob')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
