# Generated by Django 4.2.23 on 2025-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_line', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('job', 'section'), name='production_log_unique_job_section'),
        ),
    ]
