# Generated by Django 4.2.23 on 2025-10-22 11:48

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_code', models.CharField(blank=True, max_length=50, null=True)),
                ('exhibition_name', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('fabric_description', models.TextField(blank=True, null=True)),
                ('fabric_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fabric_entry_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', django_jalali.db.models.jDateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('در انتظار', 'در انتظار'), ('در حال ساخت', 'در حال ساخت'), ('در انبار', 'در انبار'), ('ارسال شده', 'ارسال شده'), ('لغو شده', 'لغو شده'), ('گارانتی', 'گارانتی')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, help_text='شناسه یکتا برای تولید کد QR سفارش.', max_length=64, null=True, unique=True, verbose_name='کد کیوآر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('job_number', models.CharField(blank=True, help_text='شماره یکتا برای پیگیری محصول در خط تولید.', max_length=64, null=True, unique=True, verbose_name='شماره کار')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
