# Generated by Django 4.2.23 on 2025-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_badge_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_stage',
            field=models.CharField(choices=[('در انتظار تولید', 'در انتظار تولید'), ('زیرکاری A', 'زیرکاری A'), ('زیرکاری B', 'زیرکاری B'), ('زیرکاری C', 'زیرکاری C'), ('رنگ\u200c\u200cکاری', 'رنگ\u200c\u200cکاری'), ('رویه\u200cکوبی', 'رویه\u200cکوبی'), ('بسته\u200cبندی', 'بسته\u200cبندی')], default='در انتظار تولید', help_text='آخرین مرحله انجام\u200cشده در خط تولید.', max_length=32, verbose_name='مرحله فعلی'),
        ),
    ]
