# Generated by Django 4.2.23 on 2025-10-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('current_section', models.CharField(blank=True, choices=[('cutting', 'برش'), ('cnc_tools', 'سی\u200cان\u200cسی و ابزار'), ('undercoating', 'رنگ زیرکار'), ('painting', 'رنگ'), ('workpage', 'صفحه\u200cکاری'), ('sewing', 'خیاطی'), ('upholstery', 'رویه\u200cکوبی'), ('assembly', 'مونتاژ'), ('packaging', 'بسته\u200cبندی')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'در حال ساخت'), ('completed', 'تولید شده'), ('scrapped', 'اسقاط'), ('warranty', 'گارانتی'), ('repaired', 'تعمیرات'), ('deposit', 'امانی')], default='in_progress', max_length=20)),
                ('job_label', models.CharField(choices=[('in_progress', 'در حال ساخت'), ('completed', 'تولید شده'), ('scrapped', 'اسقاط'), ('warranty', 'گارانتی'), ('repaired', 'تعمیرات'), ('deposit', 'امانی')], default='in_progress', max_length=20)),
                ('deposit_account', models.CharField(blank=True, max_length=100, null=True)),
                ('is_external_entry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_sections', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.orderitem')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Production Job',
                'verbose_name_plural': 'Production Jobs',
            },
        ),
    ]
